### ISSUE TITLE
Color variants in product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#13]
The color variants are coming as images in product page.
We can use colors/ swatches for the same **Suggestion**
![image](https://user-images.githubusercontent.com/97726944/172597374-f049aa18-a49a-4e99-a02a-1383dc4cdcc1.png)

**Comment by ui-abhishekkushwaha** [comment]
No issue it's all come from the migration it's not required to change
