### ISSUE TITLE
Disabled Send button in Contact Supplier form

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#14]
When we are giving valid input to the input fields the also there is disabled symbol is coming in send message button.
Video: https://www.awesomescreenshot.com/video/9339356?key=4d7942d4e497fadbd3691aaecb341f45

**Comment by ui-abhishekkushwaha** [comment]
Abhishek please check this

**Comment by Shoaibans** [comment]
Fixed
![image](https://user-images.githubusercontent.com/97726944/172996386-26964610-0ce1-4225-8284-5228c8adc383.png)
