### ISSUE TITLE
Pricing boxes in filters

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#16]
The pricing boxes are not coming proper in filter.
Collection page: 
![image](https://user-images.githubusercontent.com/97726944/172601283-041439b8-d031-48b1-9657-7322e50e10c4.png)

Search page: 
![image](https://user-images.githubusercontent.com/97726944/172601489-0200eaff-02a2-4011-b9d5-7795a7745852.png)

**Comment by ui-abhishekkushwaha** [comment]
done
