### ISSUE TITLE
Availability filter in search page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#17]
when we are applying both In stock & Out of Stock filter and when we unselect the instock then it is not removing.
Video: https://www.awesomescreenshot.com/video/9339873?key=094e439153cd15953e81cd9b33a64a6a

**Comment by devAbhishekYadav** [comment]
https://www.awesomescreenshot.com/video/9369466?key=6d6836adea31d722f9c8170f62e9f067

**Comment by Shoaibans** [comment]
@devAbhishekYadav pls check the video again and perform the same actions, apply both availability filters & remove check mark from In Stock then the loading bar is just loading.
If need any discussion pls connect with me.
