### ISSUE TITLE
Country field in address form

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#19]
The country field is not coming proper in address form.
![image](https://user-images.githubusercontent.com/97726944/172603733-19b5f552-d936-495d-8957-d954dcc7d42a.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/172792939-083e66b1-2a3d-47a4-ace6-6b39e41bf777.png)

what i find circle the input field only
