### ISSUE TITLE
Chat bot overlapping with currency converter

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#22]
The Chat bot is overlapping with currency converter in hamburger.
![image](https://user-images.githubusercontent.com/97726944/172605874-e8fe2ad7-8e9a-4eb9-8d1a-c4f31ec82879.png)

**Comment by Shoaibans** [comment]
Still coming same
![image](https://user-images.githubusercontent.com/97726944/172994754-37a7852e-1d9d-49c3-8048-bb84576d503f.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173019017-2db07cb2-cd6e-4474-95df-fc917fe79e47.png)
