### ISSUE TITLE
Missing collection images in collection/all page & same collection images in some collections (Video thumbnail)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#23]
https://paws-asia.myshopify.com/collections
![image](https://user-images.githubusercontent.com/97726944/172606592-60316be8-8479-4602-ae12-f5b98faace56.png)
![image](https://user-images.githubusercontent.com/97726944/172606641-db811691-9f5c-41cd-b84e-a352670286a1.png)
![image](https://user-images.githubusercontent.com/97726944/172606675-a4a997d9-749f-4853-a9b2-7020fbd3a921.png)

**Comment by ui-abhishekkushwaha** [comment]
blank collection remove

**Comment by Shoaibans** [comment]
Blank collections are removed but the images are coming cropped & most of the products are having video thumbnail as the collection image in All collections page.
Video: https://www.awesomescreenshot.com/video/9382261?key=32fe723c17e28c353dc4cac0f72ef484

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173315475-5bfa078b-0395-4ec3-8bac-c56410390642.png)
Issue re-solved
