### ISSUE TITLE
Search page banner is cropping

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#25]
The search page banner is coming cropped in Desktop & ipad.
![image](https://user-images.githubusercontent.com/97726944/172608002-08eeb464-a1c3-4721-a621-a6ba5b75ffd9.png)
![image](https://user-images.githubusercontent.com/97726944/172608250-6e84e8ba-31b4-43fb-b824-9200feadf7ce.png)

**Comment by Shoaibans** [comment]
Pls specify the reason for not Required

**Comment by ui-abhishekkushwaha** [comment]
not need to change the image , this is stock image for use bg only no need to concern about image cutting
