### ISSUE TITLE
Filter clear all button is not working in search page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#30]
the clear all button of filter is not working in search page (Mobile & ipad)
![image](https://user-images.githubusercontent.com/97726944/172611556-44a60741-c150-4595-9271-85ab446125dd.png)

**Comment by Shoaibans** [comment]
> https://www.awesomescreenshot.com/video/9369466?key=6d6836adea31d722f9c8170f62e9f067

@devAbhishekYadav pls check the issue in Mobile, apply the filters & click on clear all, the progress bar will come but the filter will not remove.
Video: https://www.awesomescreenshot.com/video/9377008?key=e224f05fc64c86e10b54436a8d80bb21

**Comment by Shoaibans** [comment]
@devAbhishekYadav pls check the issue in Mobile, apply the filters & click on clear all, the progress bar will come but the filter will not remove.
Video: https://www.awesomescreenshot.com/video/9377008?key=e224f05fc64c86e10b54436a8d80bb21

**Comment by Shoaibans** [comment]
@devAbhishekYadav now the button is working but after clearing the filters the products are not coming, the page is redirecting to the search bar.
Video: https://www.awesomescreenshot.com/video/9411424?key=5c2bddadcef80eb8ee2c00361c804837

**Comment by devAbhishekYadav** [comment]
@Shoaibans pls check now
