### ISSUE TITLE
Content in contact page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#33]
We can remove the word "below" from the content becoz, the form is coming to the keft in Desktop & ipad and for mobile the form is coming above the content, so we can remove the word below.
![image](https://user-images.githubusercontent.com/97726944/172612792-98b02beb-ce29-4331-8fda-6c21b7e54934.png)

**Comment by Shoaibans** [comment]
Not fixed
![image](https://user-images.githubusercontent.com/97726944/172996733-560c9712-fc64-49f5-b29c-e5e442cbebbd.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173017383-ca68bc1d-df54-413e-8eab-24136f80a6e1.png)
