### ISSUE TITLE
Add to cart button missing from wishlist

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#40]
![image](https://user-images.githubusercontent.com/97726944/172619179-ac89a7da-a2a6-474a-bdfb-c7b79cb27c03.png)

**Comment by devAbhishekYadav** [comment]
This has been done intentionally to avoid any redirection to cart page

**Comment by Shoaibans** [comment]
@devAbhishekYadav But Add All To Cart in wishslist is redirecting to the cart page.
