### ISSUE TITLE
Extra Spacing in Mac device Homepage

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#41]
Extra spacing is coming in Mac device homepage below the Testimonials 
![image](https://user-images.githubusercontent.com/97726944/172769960-a22fd863-60b4-4e02-bf23-af83ffa604e7.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/172998854-64bfe919-d09f-4e88-ac97-a81c73bbcafc.png)
is not coming i also checked in mac

**Comment by Shoaibans** [comment]
Not an issue, checked in real device.
