### ISSUE TITLE
Button Arrows alignment in collection page (MAC)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#42]
The arrows are not coming properly aligned in Mac device collection page.
![image](https://user-images.githubusercontent.com/97726944/172770626-8d70228d-e258-4688-9b6b-bebb2f2b9d20.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173001898-b8feaa67-9f66-4945-9ad0-e644d28cc939.png)
no issue showing check the image

**Comment by Shoaibans** [comment]
Not an issue, checked in real device
![image](https://user-images.githubusercontent.com/97726944/173041897-9ba7db7b-a1cb-4e7c-87a5-e85600d1ba8c.png)
