### ISSUE TITLE
Description (?) icon is overlapping in product page (MAC)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#43]
The question icon is overlapping with the text in product page in Mac device.
![image](https://user-images.githubusercontent.com/97726944/172771496-61296ed6-d85d-42da-828e-0ccaa9ab4aa2.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173001653-25bf8bf5-db37-4c24-b04e-b54c2d7d41f4.png)
not showing issue

**Comment by Shoaibans** [comment]
Not an issue, checked in real device
![image](https://user-images.githubusercontent.com/97726944/173042118-94e3d14e-2298-420a-a471-a8b6be7db773.png)
