### ISSUE TITLE
Wishlist icon alignment in product page You may also like section (MAC)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#44]
The wishlist icon is coming unorganized in you may also like section in Mac device. 
![image](https://user-images.githubusercontent.com/97726944/172771776-c71765d1-a155-43c0-92b8-ea388ff75b6a.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173000545-b1204fb4-a558-4009-b0f7-3f6daf6eaca2.png)
not showing any issue

**Comment by Shoaibans** [comment]
Not an issue, checked in real device.
![image](https://user-images.githubusercontent.com/97726944/173042444-c3f3c489-c9db-4d38-80b6-2bc62f15d43c.png)
