### ISSUE TITLE
Input field texts overlapping in contact form (Mac)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#46]
The input field texts are overlapping with the inputs in contact form (Mac)
![image](https://user-images.githubusercontent.com/97726944/172773273-f6ce18da-8a8d-4dcd-9f58-70f7417fd38e.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173004265-95bc9cad-d37a-4d96-8753-bd1bc13ed24f.png)
No issue

**Comment by Shoaibans** [comment]
![image](https://user-images.githubusercontent.com/97726944/173043131-7848291a-f682-4671-ae73-53d67d95cbab.png)
