### ISSUE TITLE
Product page Overview Description is cropping in different resolutions (mobile)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#49]
pls check the video for the issue: https://www.awesomescreenshot.com/video/9378719?key=8b020fafd02f9843b47e4784d88cabb8

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173034264-ed6c2f65-d61e-4ed6-af39-aa957a0065fa.png)
