### ISSUE TITLE
Spacing in product page (Mobile)

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#50]
The spacing between the thumbnails & product title can be reduced.
![image](https://user-images.githubusercontent.com/97726944/173014560-f3a1f055-5092-4980-a5e7-1feee09f1f0b.png)

**Comment by Shoaibans** [comment]
Pls specify the reason for not Required

**Comment by ui-abhishekkushwaha** [comment]
i don't think there is an issue that's why i do the not required
