### ISSUE TITLE
The video thumbnail is coming as the image in collection pages products

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#6]
The video thumbnail is coming as the image in collection pages products until we hover over them.
![image](https://user-images.githubusercontent.com/97726944/172592325-ad311020-7412-4ce8-a0b6-313c9075c504.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/173017661-2a8bad77-2ce2-488a-b805-26ce5c1c4d2a.png)
