### ISSUE TITLE
Missing swatches color

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#7]
For some of the products the color of swatches are missing in all the pages.
![image](https://user-images.githubusercontent.com/97726944/172592612-9d626389-7a1b-44a7-8bef-2bb98dab267e.png)
![image](https://user-images.githubusercontent.com/97726944/172592777-319bc5b4-6877-4587-b709-8c6891a99592.png)
![image](https://user-images.githubusercontent.com/97726944/172593077-3d733ecb-eaea-4dec-b487-8f3774118ae4.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/172784722-73a6d3a6-978e-40d4-9053-fa5f1f2dbd6b.png)
color code come into another code that's why it is not showing the actual color the client will change this according to his color in future
