### ISSUE TITLE
Missing swatches color from filter

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yu-Huan---Internal-Store-Redesign-Migration-#8]
The swatches colors are not coming in color filter.
![image](https://user-images.githubusercontent.com/97726944/172593407-c04af205-5bd0-4821-a869-82096f8307e2.png)

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/172784722-73a6d3a6-978e-40d4-9053-fa5f1f2dbd6b.png)
color code come into another code that's why it is not showing the actual color the client will change this according to his color in future
